# Generated by Django 3.2.4 on 2021-06-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
