# Generated by Django 3.1.3 on 2021-01-13 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='cuisine_id',
            new_name='cuisine',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='food_category_id',
            new_name='food_category',
        ),
    ]
