# Generated by Django 3.1.3 on 2021-01-14 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20210113_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_table', to='back.course'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisine_table', to='back.cuisine'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='food_category',
        ),
        migrations.AddField(
            model_name='recipe',
            name='food_category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='food_category_table', to='back.course'),
            preserve_default=False,
        ),
    ]
