# Generated by Django 3.1.3 on 2021-01-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_auto_20210114_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
