# Generated by Django 3.1.3 on 2021-01-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_auto_20210120_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub',
            field=models.CharField(default='', max_length=70, unique=True),
        ),
    ]
