# Generated by Django 3.1.3 on 2021-01-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_user_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
