# Generated by Django 3.1.3 on 2021-01-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_recipe_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.CharField(default='', max_length=150),
        ),
    ]
